version: '3.4'

services:
  restapi:
    image: restapi
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://root:123456@localhost:3306/rest-api
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
