version: '3.4'

services:
  restapi:
    image: restapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://root:123456@db/rest_api
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - "db"
    networks:
      - rest-api      
  db:
    image: mysql:8.0.28
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: rest_api
    networks:
      - rest-api
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456 
    networks:
      - rest-api      
networks:
  rest-api:
volumes:
  db_data: {}       